sign: lalka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tinkoff-kotlin-psql-1.postgres.database.azure.com:5432/fintech?currentSchema=cashback
    username: kotlin_master@tinkoff-kotlin-psql-1
    password: koklin
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

kafka:
  consumer:
    bootstrapServers: 40.69.78.245:19092
    topic: transactions
    groupId: cashback

service.url:
  card: http://13.79.17.165/card-service/api/v1/card/
  client: http://13.79.17.165/client-service/api/v1/client/
  loyaly: http://13.79.17.165/loyalty-service/api/v1/program/
  notification: http://13.79.17.165/notification-service/api/v2/client/